id: opecha:P007082
initial_creation_type: ocr
source_metadata:
  id: bdr:W19962
  title: བོད་ཀྱི་འབྱུང་བ་བརྗོད་པའི་འབེལ་གཏམ།
  volume:
    6450eac2f0484986b76c9f77adbaa2d4:
      image_group_id: I1KG13540
      title: Volume 1 of bod kyi 'byung ba brjod pa'i 'bel gtam/
      volume_number: 1
      total_pages: 200
  author: ''
ebook_metadata:
  title: བོད་ཀྱི་འབྱུང་བ་བརྗོད་པའི་འབེལ་གཏམ།
  author: ''
  sku: P007082
  cover: cover.jpg
  layers:
  - pagination
