id: P007082
initial_creation_type: ocr
source_metadata:
  id: bdr:W19962
  title: བོད་ཀྱི་འབྱུང་བ་བརྗོད་པའི་འབེལ་གཏམ།
  author: ''
  volumes:
    8172f65476b14bcf8913d42cb15ee9ce:
      image_group_id: I1KG13540
      title: ''
      volume_number: 1
      total_pages: 200
ebook_metadata:
  title: བོད་ཀྱི་འབྱུང་བ་བརྗོད་པའི་འབེལ་གཏམ།
  author: ''
  sku: P007082
  cover: cover.jpg
  layers:
  - pagination
